[package]
name = "webloc"
version = "1.1.0"
edition = "2018"

[dependencies]
semver = "1"

[dependencies.serde]
version = "1"
features = ["derive"]

[dependencies.url]
version = "2"
features = ["serde"]
